import type { CruiseLine } from "@/lib/types";

/**
 * Contemporary and mass-market lines — where the overwhelming majority of
 * advisor bookings actually land.
 *
 * ROSTER SNAPSHOT, not verified fact. Fleets move constantly: new builds
 * enter service, hulls transfer between sister brands, older ships leave.
 * This list is a starting point for the picker, not a source of truth —
 * check it against the line's current fleet page before relying on it.
 *
 * Nothing here produces a Confidence Read on its own. A ship only returns
 * a read once it has operator content in src/content/reads.
 */
export const CONTEMPORARY_LINES: CruiseLine[] = [
  {
    id: "carnival",
    name: "Carnival",
    category: "contemporary",
    ships: [
      { name: "Carnival Mardi Gras", shipClass: "Excel" },
      { name: "Carnival Celebration", shipClass: "Excel" },
      { name: "Carnival Jubilee", shipClass: "Excel" },
      { name: "Carnival Venezia", shipClass: "Vista (Costa)" },
      { name: "Carnival Firenze", shipClass: "Vista (Costa)" },
      { name: "Carnival Vista", shipClass: "Vista" },
      { name: "Carnival Horizon", shipClass: "Vista" },
      { name: "Carnival Panorama", shipClass: "Vista" },
      { name: "Carnival Dream", shipClass: "Dream" },
      { name: "Carnival Magic", shipClass: "Dream" },
      { name: "Carnival Breeze", shipClass: "Dream" },
      // A Costa Concordia-class hull completed for Carnival in 2008 —
      // commonly miscalled a stretched Conquest. Its sisters are all Costa.
      { name: "Carnival Splendor", shipClass: "Concordia" },
      { name: "Carnival Conquest", shipClass: "Conquest" },
      { name: "Carnival Glory", shipClass: "Conquest" },
      { name: "Carnival Valor", shipClass: "Conquest" },
      { name: "Carnival Liberty", shipClass: "Conquest" },
      { name: "Carnival Freedom", shipClass: "Conquest" },
      { name: "Carnival Spirit", shipClass: "Spirit" },
      { name: "Carnival Pride", shipClass: "Spirit" },
      { name: "Carnival Legend", shipClass: "Spirit" },
      { name: "Carnival Miracle", shipClass: "Spirit" },
      // Built as Costa Luminosa (2009) to a Vista/Spirit hybrid design and
      // transferred in 2022. Routinely listed as Spirit class, and bigger
      // in tonnage and beam than the four hulls that actually are.
      { name: "Carnival Luminosa", shipClass: "Vista/Spirit hybrid" },
      { name: "Carnival Sunshine", shipClass: "Sunshine" },
      { name: "Carnival Sunrise", shipClass: "Sunshine" },
      { name: "Carnival Radiance", shipClass: "Sunshine" },
      { name: "Carnival Elation", shipClass: "Fantasy" },
      { name: "Carnival Paradise", shipClass: "Fantasy" },
      // Grand-class Princess hulls (Golden Princess 2001, Star Princess
      // 2002) via P&O Australia, moved to the Carnival brand in 2025.
      { name: "Carnival Adventure", shipClass: "Grand (ex-P&O)" },
      { name: "Carnival Encounter", shipClass: "Grand (ex-P&O)" },
    ],
  },
  {
    id: "royal-caribbean",
    name: "Royal Caribbean",
    category: "contemporary",
    ships: [
      { name: "Icon of the Seas", shipClass: "Icon" },
      { name: "Star of the Seas", shipClass: "Icon" },
      { name: "Legend of the Seas", shipClass: "Icon" },
      { name: "Oasis of the Seas", shipClass: "Oasis" },
      { name: "Allure of the Seas", shipClass: "Oasis" },
      { name: "Harmony of the Seas", shipClass: "Oasis" },
      { name: "Symphony of the Seas", shipClass: "Oasis" },
      { name: "Wonder of the Seas", shipClass: "Oasis" },
      { name: "Utopia of the Seas", shipClass: "Oasis" },
      { name: "Quantum of the Seas", shipClass: "Quantum" },
      { name: "Anthem of the Seas", shipClass: "Quantum" },
      { name: "Ovation of the Seas", shipClass: "Quantum" },
      { name: "Spectrum of the Seas", shipClass: "Quantum Ultra" },
      { name: "Odyssey of the Seas", shipClass: "Quantum Ultra" },
      { name: "Freedom of the Seas", shipClass: "Freedom" },
      { name: "Liberty of the Seas", shipClass: "Freedom" },
      { name: "Independence of the Seas", shipClass: "Freedom" },
      { name: "Voyager of the Seas", shipClass: "Voyager" },
      { name: "Explorer of the Seas", shipClass: "Voyager" },
      { name: "Adventure of the Seas", shipClass: "Voyager" },
      { name: "Navigator of the Seas", shipClass: "Voyager" },
      { name: "Mariner of the Seas", shipClass: "Voyager" },
      { name: "Radiance of the Seas", shipClass: "Radiance" },
      { name: "Brilliance of the Seas", shipClass: "Radiance" },
      { name: "Serenade of the Seas", shipClass: "Radiance" },
      { name: "Jewel of the Seas", shipClass: "Radiance" },
      { name: "Grandeur of the Seas", shipClass: "Vision" },
      { name: "Enchantment of the Seas", shipClass: "Vision" },
      { name: "Rhapsody of the Seas", shipClass: "Vision" },
      { name: "Vision of the Seas", shipClass: "Vision" },
    ],
  },
  {
    id: "norwegian",
    name: "Norwegian",
    category: "contemporary",
    ships: [
      { name: "Norwegian Prima", shipClass: "Prima" },
      { name: "Norwegian Viva", shipClass: "Prima" },
      { name: "Norwegian Aqua", shipClass: "Prima Plus" },
      { name: "Norwegian Luna", shipClass: "Prima Plus" },
      { name: "Norwegian Escape", shipClass: "Breakaway Plus" },
      { name: "Norwegian Joy", shipClass: "Breakaway Plus" },
      { name: "Norwegian Bliss", shipClass: "Breakaway Plus" },
      { name: "Norwegian Encore", shipClass: "Breakaway Plus" },
      { name: "Norwegian Breakaway", shipClass: "Breakaway" },
      { name: "Norwegian Getaway", shipClass: "Breakaway" },
      { name: "Norwegian Epic", shipClass: "Epic" },
      { name: "Norwegian Jewel", shipClass: "Jewel" },
      { name: "Norwegian Jade", shipClass: "Jewel" },
      { name: "Norwegian Pearl", shipClass: "Jewel" },
      { name: "Norwegian Gem", shipClass: "Jewel" },
      { name: "Norwegian Dawn", shipClass: "Dawn" },
      { name: "Norwegian Star", shipClass: "Dawn" },
      { name: "Norwegian Sun", shipClass: "Sun" },
      { name: "Norwegian Sky", shipClass: "Sky" },
      { name: "Norwegian Spirit", shipClass: "Spirit" },
    ],
  },
  {
    id: "msc",
    name: "MSC Cruises",
    category: "contemporary",
    ships: [
      { name: "MSC World Europa", shipClass: "World" },
      { name: "MSC World America", shipClass: "World" },
      { name: "MSC Meraviglia", shipClass: "Meraviglia" },
      { name: "MSC Bellissima", shipClass: "Meraviglia" },
      { name: "MSC Grandiosa", shipClass: "Meraviglia Plus" },
      { name: "MSC Virtuosa", shipClass: "Meraviglia Plus" },
      { name: "MSC Euribia", shipClass: "Meraviglia Plus" },
      { name: "MSC Seaside", shipClass: "Seaside" },
      { name: "MSC Seaview", shipClass: "Seaside" },
      { name: "MSC Seashore", shipClass: "Seaside Evo" },
      { name: "MSC Seascape", shipClass: "Seaside Evo" },
      { name: "MSC Fantasia", shipClass: "Fantasia" },
      { name: "MSC Splendida", shipClass: "Fantasia" },
      { name: "MSC Divina", shipClass: "Fantasia" },
      { name: "MSC Preziosa", shipClass: "Fantasia" },
      { name: "MSC Musica", shipClass: "Musica" },
      { name: "MSC Poesia", shipClass: "Musica" },
      { name: "MSC Orchestra", shipClass: "Musica" },
      { name: "MSC Magnifica", shipClass: "Musica" },
      { name: "MSC Lirica", shipClass: "Lirica" },
      { name: "MSC Opera", shipClass: "Lirica" },
      { name: "MSC Armonia", shipClass: "Lirica" },
      { name: "MSC Sinfonia", shipClass: "Lirica" },
    ],
  },
  {
    id: "costa",
    name: "Costa Cruises",
    category: "contemporary",
    ships: [
      { name: "Costa Smeralda", shipClass: "Excellence" },
      { name: "Costa Toscana", shipClass: "Excellence" },
      { name: "Costa Diadema", shipClass: "Diadema" },
      { name: "Costa Fascinosa", shipClass: "Concordia" },
      { name: "Costa Favolosa", shipClass: "Concordia" },
      { name: "Costa Deliziosa", shipClass: "Spirit" },
      { name: "Costa Fortuna", shipClass: "Destiny" },
      { name: "Costa Pacifica", shipClass: "Concordia" },
      { name: "Costa Serena", shipClass: "Concordia" },
    ],
  },
  {
    id: "disney",
    name: "Disney Cruise Line",
    category: "contemporary",
    ships: [
      { name: "Disney Magic", shipClass: "Magic" },
      { name: "Disney Wonder", shipClass: "Magic" },
      { name: "Disney Dream", shipClass: "Dream" },
      { name: "Disney Fantasy", shipClass: "Dream" },
      { name: "Disney Wish", shipClass: "Wish" },
      { name: "Disney Treasure", shipClass: "Wish" },
      { name: "Disney Destiny", shipClass: "Wish" },
      { name: "Disney Adventure", shipClass: "Global" },
    ],
  },
  {
    id: "virgin-voyages",
    name: "Virgin Voyages",
    category: "contemporary",
    ships: [
      { name: "Scarlet Lady", shipClass: "Lady" },
      { name: "Valiant Lady", shipClass: "Lady" },
      { name: "Resilient Lady", shipClass: "Lady" },
      { name: "Brilliant Lady", shipClass: "Lady" },
    ],
  },
  {
    id: "po-cruises",
    name: "P&O Cruises",
    category: "contemporary",
    ships: [
      { name: "Iona", shipClass: "Excellence" },
      { name: "Arvia", shipClass: "Excellence" },
      { name: "Britannia", shipClass: "Britannia" },
      { name: "Ventura", shipClass: "Grand" },
      { name: "Azura", shipClass: "Grand" },
      { name: "Aurora", shipClass: "Aurora" },
      { name: "Arcadia", shipClass: "Vista" },
    ],
  },
];
